/* MateShot video export v2: faster render, monotonic motion and full localization. */
(() => {
  const LANG = (navigator.language || 'en').toLowerCase().startsWith('es') ? 'es' : 'en';
  const TXT = LANG === 'es' ? {
    sideB:'Mueven negras', sideW:'Mueven blancas', forced:'Mate forzado en', mate:'Mate en', checkmate:'Jaque mate',
    rendering:'Creando vídeo…', downloaded:'Vídeo descargado', unsupported:'Este navegador todavía no permite exportar el vídeo.', copied:'Solución copiada'
  } : {
    sideB:'Black to move', sideW:'White to move', forced:'Forced mate in', mate:'Mate in', checkmate:'Checkmate',
    rendering:'Building video…', downloaded:'Video downloaded', unsupported:'Video export is not supported by this browser yet.', copied:'Solution copied'
  };
  const PIECE_BASE='https://lichess1.org/assets/piece/cburnett/';
  const pieceCode=p=>(p===p.toUpperCase()?'w':'b')+p.toUpperCase();
  const pieceSrc=p=>PIECE_BASE+pieceCode(p)+'.svg';
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  function toast2(msg){const el=document.getElementById('toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(toast2._t);toast2._t=setTimeout(()=>el.classList.remove('show'),1800);}
  function preloadPiecesFast(){if(preloadPiecesFast.cache)return preloadPiecesFast.cache;const chars=['K','Q','R','B','N','P','k','q','r','b','n','p'];preloadPiecesFast.cache=Promise.all(chars.map(p=>new Promise((resolve,reject)=>{const im=new Image();im.crossOrigin='anonymous';im.onload=()=>resolve([p,im]);im.onerror=reject;im.src=pieceSrc(p);}))).then(x=>Object.fromEntries(x));return preloadPiecesFast.cache;}
  function canvasSquare(index,orientation,bx,by,cell){let r=(index/8)|0,c=index%8;if(orientation==='black'){r=7-r;c=7-c;}return{x:bx+c*cell,y:by+r*cell};}
  function easeInOutQuad(p){return p<0.5?2*p*p:1-Math.pow(-2*p+2,2)/2;}
  function currentMoveLabel(index){if(!S?.line?.[index])return'';const mv=S.line[index],startsBlack=S.start.side==='b';if(startsBlack){if(index===0)return'1… '+mv.san;const n=Math.floor((index+1)/2)+1;return index%2===1?n+'. '+mv.san:n+'… '+mv.san;}const n=Math.floor(index/2)+1;return index%2===0?n+'. '+mv.san:n+'… '+mv.san;}
  function drawFrame(ctx,images,position,orientation,move=null,p=1,label=''){
    const W=720,H=900,board=600,bx=60,by=112,cell=board/8;ctx.fillStyle='#090b0d';ctx.fillRect(0,0,W,H);ctx.fillStyle='#d6ff58';ctx.beginPath();ctx.arc(44,43,5.5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f5f6f2';ctx.font='800 30px -apple-system,BlinkMacSystemFont,Arial';ctx.fillText('MateShot',60,52);ctx.fillStyle='#a9b0b8';ctx.font='600 16px -apple-system,BlinkMacSystemFont,Arial';const side=S.start.side==='b'?TXT.sideB:TXT.sideW;ctx.fillText(side+'  ·  '+TXT.forced+' '+S.mateN,60,82);
    for(let vr=0;vr<8;vr++)for(let vc=0;vc<8;vc++){ctx.fillStyle=((vr+vc)&1)?'#b98c68':'#f0d9b5';ctx.fillRect(bx+vc*cell,by+vr*cell,cell,cell);}
    if(move){const hs=canvasSquare(move.from,orientation,bx,by,cell),ht=canvasSquare(move.to,orientation,bx,by,cell);ctx.fillStyle='rgba(214,255,88,.24)';ctx.fillRect(hs.x,hs.y,cell,cell);ctx.fillStyle='rgba(214,255,88,.43)';ctx.fillRect(ht.x,ht.y,cell,cell);}
    const b=position.b,moving=move?b[move.from]:null;for(let i=0;i<64;i++){const pc=b[i];if(!pc)continue;if(move&&(i===move.from||i===move.to))continue;const q=canvasSquare(i,orientation,bx,by,cell);ctx.drawImage(images[pc],q.x+cell*.055,q.y+cell*.055,cell*.89,cell*.89);}
    if(move){const captured=b[move.to];if(captured&&p<0.82){const z=canvasSquare(move.to,orientation,bx,by,cell);ctx.drawImage(images[captured],z.x+cell*.055,z.y+cell*.055,cell*.89,cell*.89);}const a=canvasSquare(move.from,orientation,bx,by,cell),z=canvasSquare(move.to,orientation,bx,by,cell),e=easeInOutQuad(Math.max(0,Math.min(1,p))),x=a.x+(z.x-a.x)*e,y=a.y+(z.y-a.y)*e;if(moving)ctx.drawImage(images[moving],x+cell*.055,y+cell*.055,cell*.89,cell*.89);}
    ctx.fillStyle='#f5f6f2';ctx.font='800 29px -apple-system,BlinkMacSystemFont,Arial';ctx.fillText(TXT.mate+' '+S.mateN,60,765);ctx.fillStyle='#c6ccd3';ctx.font='650 20px -apple-system,BlinkMacSystemFont,Arial';ctx.fillText(label||'',60,803,570);ctx.fillStyle='#6f7781';ctx.font='700 16px -apple-system,BlinkMacSystemFont,Arial';ctx.textAlign='right';ctx.fillText('MateShot',660,862);ctx.textAlign='left';
  }
  async function buildVideoFast(){if(!S?.positions?.length||!S?.line?.length)throw new Error('No solution');const key=S.orientation+'|'+S.start.side+'|'+S.mateN+'|'+notation(S.line,S.start.side);if(S.fastVideoBlob&&S.fastVideoKey===key)return{blob:S.fastVideoBlob,mime:S.fastVideoMime};const canvas=document.createElement('canvas');canvas.width=720;canvas.height=900;const ctx=canvas.getContext('2d',{alpha:false});if(!canvas.captureStream||!window.MediaRecorder)throw new Error(TXT.unsupported);const images=await preloadPiecesFast();const candidates=['video/mp4;codecs=avc1.42E01E','video/mp4','video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'],mime=candidates.find(x=>MediaRecorder.isTypeSupported?.(x))||'',fps=24,stream=canvas.captureStream(fps),chunks=[],opts={videoBitsPerSecond:2200000};if(mime)opts.mimeType=mime;const rec=new MediaRecorder(stream,opts);rec.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data);};const stopped=new Promise((resolve,reject)=>{rec.onstop=resolve;rec.onerror=e=>reject(e.error||e);});rec.start(200);drawFrame(ctx,images,S.positions[0],S.orientation,null,1,'');await sleep(300);const moveMs=420,holdMs=90;for(let i=0;i<S.line.length;i++){const frames=Math.max(7,Math.round(moveMs/1000*fps)),before=S.positions[i],mv=S.line[i],moveLabel=currentMoveLabel(i);for(let f=0;f<frames;f++){const p=frames===1?1:f/(frames-1);drawFrame(ctx,images,before,S.orientation,mv,p,moveLabel);await sleep(1000/fps);}drawFrame(ctx,images,S.positions[i],S.orientation,mv,1,moveLabel);await sleep(holdMs);}drawFrame(ctx,images,S.positions[S.positions.length-2],S.orientation,S.line[S.line.length-1],1,TXT.checkmate);await sleep(450);rec.stop();await stopped;stream.getTracks().forEach(x=>x.stop());const actual=mime||rec.mimeType||'video/webm',blob=new Blob(chunks,{type:actual});S.fastVideoKey=key;S.fastVideoBlob=blob;S.fastVideoMime=actual;return{blob,mime:actual};}
  const ext=mime=>mime.includes('mp4')?'mp4':'webm';
  function solutionText(){const rows=[];if(S.start.side==='b'){rows.push('1… '+S.line[0].san);let no=2;for(let i=1;i<S.line.length;i+=2,no++)rows.push(no+'. '+S.line[i].san+(S.line[i+1]?' '+S.line[i+1].san:''));}else{let no=1;for(let i=0;i<S.line.length;i+=2,no++)rows.push(no+'. '+S.line[i].san+(S.line[i+1]?' '+S.line[i+1].san:''));}return TXT.mate+' '+S.mateN+'\n'+rows.join('\n');}
  async function downloadFast(){const btn=document.getElementById('download'),label=btn?.querySelector('span'),note=document.getElementById('exportNote');if(!btn||!label)return;const old=label.textContent;label.textContent=TXT.rendering;btn.disabled=true;if(note)note.textContent='';try{const{blob,mime}=await buildVideoFast(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mateshot-mate-'+S.mateN+'.'+ext(mime);document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),4000);toast2(TXT.downloaded);}catch(e){if(note)note.textContent=e.message||TXT.unsupported;}finally{btn.disabled=false;label.textContent=old;}}
  async function shareFast(){const btn=document.getElementById('share'),label=btn?.querySelector('span'),note=document.getElementById('exportNote');if(!btn||!label)return;const old=label.textContent;label.textContent=TXT.rendering;btn.disabled=true;if(note)note.textContent='';try{const{blob,mime}=await buildVideoFast(),file=new File([blob],'mateshot-mate-'+S.mateN+'.'+ext(mime),{type:mime});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'MateShot',text:solutionText()});else if(navigator.share)await navigator.share({title:'MateShot',text:solutionText()});else{await navigator.clipboard.writeText(solutionText());toast2(TXT.copied);}}catch(e){if(e?.name!=='AbortError'&&note)note.textContent=e.message||TXT.unsupported;}finally{btn.disabled=false;label.textContent=old;}}
  const download=document.getElementById('download'),share=document.getElementById('share');if(download)download.onclick=downloadFast;if(share)share.onclick=shareFast;const result=document.getElementById('result');if(result){const observer=new MutationObserver(()=>{if(result.classList.contains('active'))preloadPiecesFast().catch(()=>{});});observer.observe(result,{attributes:true,attributeFilter:['class']});}
})();
/* MateShot replay v3: smooth in-browser piece motion + matching highlights. */
(() => {
  const lang=(navigator.language||'en').toLowerCase().startsWith('es')?'es':'en';
  const LABELS=lang==='es'?{play:'Ver solución',pause:'Pausa'}:{play:'Play solution',pause:'Pause'};
  const PIECE_BASE='https://lichess1.org/assets/piece/cburnett/';
  const pieceCode=p=>(p===p.toUpperCase()?'w':'b')+p.toUpperCase();
  const pieceSrc=p=>PIECE_BASE+pieceCode(p)+'.svg';
  const style=document.createElement('style');style.textContent=`#board{position:relative}.webMoveOverlay{position:absolute;z-index:8;pointer-events:none;will-change:transform;object-fit:contain;filter:drop-shadow(0 1px 1px rgba(0,0,0,.16))}.solutionRow.active{background:rgba(214,255,88,.11);border-color:rgba(214,255,88,.28)}.solutionRow.active .n{color:#d6ff58}`;document.head.appendChild(style);
  let animToken=0,animState=null;
  function ease(p){return p<.5?4*p*p*p:1-Math.pow(-2*p+2,3)/2;}
  function visualIndex(index){return S.orientation==='black'?63-index:index;}
  function cellFor(index){return document.getElementById('board')?.children?.[visualIndex(index)]||null;}
  function activeRowForMove(i){if(i<0)return-1;return S.start?.side==='b'?(i===0?0:Math.floor((i+1)/2)):Math.floor(i/2);}
  function markActiveMove(i){const rows=[...document.querySelectorAll('#solutionList .solutionRow')],row=activeRowForMove(i);rows.forEach((el,n)=>el.classList.toggle('active',n===row));}
  function playLabel(){const b=document.getElementById('play');if(b)b.innerHTML='▶ <span>'+LABELS.play+'</span>';}
  function pauseLabel(){const b=document.getElementById('play');if(b)b.innerHTML='❚❚ <span>'+LABELS.pause+'</span>';}
  function settleAnimation(){if(!animState)return;const a=animState;S.step=a.progress>=.5?a.toStep:a.fromStep;const last=S.step?S.line[S.step-1]:null;renderBoard(S.positions[S.step].b,S.orientation,last);markActiveMove(S.step-1);animState=null;}
  window.stopPlay=stopPlay=function(){S.playing=false;clearTimeout(S.timer);S.timer=null;animToken++;settleAnimation();playLabel();};
  window.gotoStep=gotoStep=function(n){animToken++;animState=null;S.step=Math.max(0,Math.min(S.positions.length-1,n));const last=S.step?S.line[S.step-1]:null;renderBoard(S.positions[S.step].b,S.orientation,last);markActiveMove(S.step-1);};
  async function animateForward(fromStep){if(fromStep>=S.positions.length-1)return false;const token=++animToken,mv=S.line[fromStep],before=S.positions[fromStep],after=S.positions[fromStep+1];renderBoard(before.b,S.orientation,mv);markActiveMove(fromStep);await new Promise(requestAnimationFrame);const root=document.getElementById('board'),src=cellFor(mv.from),dst=cellFor(mv.to);if(!root||!src||!dst){S.step=fromStep+1;renderBoard(after.b,S.orientation,mv);return true;}const srcImg=src.querySelector('.pieceImg'),dstImg=dst.querySelector('.pieceImg'),moving=before.b[mv.from];if(!moving){S.step=fromStep+1;renderBoard(after.b,S.orientation,mv);return true;}const rr=root.getBoundingClientRect(),sr=src.getBoundingClientRect(),dr=dst.getBoundingClientRect();if(srcImg)srcImg.style.visibility='hidden';const overlay=document.createElement('img');overlay.className='webMoveOverlay';overlay.src=pieceSrc(moving);overlay.draggable=false;const pad=sr.width*.06;overlay.style.left=(sr.left-rr.left+pad)+'px';overlay.style.top=(sr.top-rr.top+pad)+'px';overlay.style.width=(sr.width-pad*2)+'px';overlay.style.height=(sr.height-pad*2)+'px';root.appendChild(overlay);const dx=dr.left-sr.left,dy=dr.top-sr.top,duration=430,start=performance.now();animState={fromStep,toStep:fromStep+1,progress:0};await new Promise(resolve=>{function frame(now){if(token!==animToken){overlay.remove();resolve();return;}const p=Math.max(0,Math.min(1,(now-start)/duration));animState.progress=p;const e=ease(p);overlay.style.transform=`translate3d(${dx*e}px,${dy*e}px,0)`;if(dstImg)dstImg.style.visibility=p<.82?'visible':'hidden';if(p<1)requestAnimationFrame(frame);else{overlay.remove();resolve();}}requestAnimationFrame(frame);});if(token!==animToken)return false;animState=null;S.step=fromStep+1;renderBoard(after.b,S.orientation,mv);markActiveMove(fromStep);return true;}
  window.playLoop=playLoop=async function(){if(!S.playing)return;if(S.step>=S.positions.length-1){stopPlay();return;}const ok=await animateForward(S.step);if(!ok||!S.playing)return;S.timer=setTimeout(playLoop,120);};
  window.togglePlay=togglePlay=function(){if(S.playing){stopPlay();return;}if(S.step>=S.positions.length-1)gotoStep(0);S.playing=true;pauseLabel();S.timer=setTimeout(playLoop,100);};
  const play=document.getElementById('play');if(play)play.onclick=togglePlay;const prev=document.getElementById('prev'),next=document.getElementById('next');if(prev)prev.onclick=()=>{stopPlay();gotoStep(S.step-1);};if(next)next.onclick=async()=>{stopPlay();if(S.step<S.positions.length-1)await animateForward(S.step);};markActiveMove((S?.step||0)-1);
})();
