/* Solve prototype: fully local board detection, Chess.com-style recognition and mate search. */
const $=id=>document.getElementById(id);
const SCREENS=['home','processing','result','error'];
const GLYPH={K:'♔',Q:'♕',R:'♖',B:'♗',N:'♘',P:'♙',k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'};
const TYPES=['k','q','r','b','n','p'];
const TEMPLATE64={
 r:'AAAAAAAAAAAAB+AAAOfnAAHn54AB9++AAf//gAH//4AB//+AAf//gAD//wAAf/4AAH/8AAB//gAAf/4AAH/+AAB//gAAf/4AAH/+AAB//gAA//4AAP//AAD//wAB//+AA///wAf//+AH///gB///4Af//+AH///gAAAAAAAAAAA=',
 q:'AAAAAAAAAAAAODwAAH5+AAD+fgAA/v4AAH5+AAw8fDAfPnj4Pz58/D8+/Pw/P/z8Hz/9+A+///AP///gB///4Af//8AD///AA///wAH//4AB//+AAP//AAD//wAA//8AAf//gAP//8AD///AB///wAf//8AH///AAAAAAAAAAAA=',
 b:'AAAAAAAAAAAAA4AAAAfgAAAH4AAAB8AAAAeAAAAPkAAAH7gAAD88AAA/fAAAf34AAH5/AAD+fwAA/n8AAP5/AAD//wAA//+AAP//AAD//wAA//8AAH/+AAB//gAAP/wAAf//gAH//4AD///AA///wAP//8AD///AAAAAAAAAAAA=',
 n:'AAAAAAAAAAAAOAAAADwAAAA/AAAAf8AAAP/wAAH/+AAB//wAAf/+AAP//wAD//8AB///AA///4AP//+AH/3/gB/z/4Afx/+AD4//gAAf/4AAP/+AAD//AAB//wAAf/8AAe/3kAP//+AD///wA///wAP//8AD///AAAAAAAAAAAA=',
 k:'AAAAAAAAAAAAB8AAAAfAAAAf8AAAH/AAAB/wAAAf8AAAB8AAA///gA///+Af///wH///8D////g////4P4/j+D+Pw/g/j8f4H8/H8B////AP///gB///gAP//4AB//8AAf//AAN//YAH//+AB///wAf//8AH///AAAAAAAAAAAA=',
 p:'AAAAAAAAAAAAA8AAAA/wAAAf+AAAH/gAAD/8AAA//AAAP/wAAD/8AAAf+AAAH/gAAB/4AAA3/gAAf/4AAD/+AAA//AAAD/AAAA/wAAAf+AAAH/wAAD/+AAB//gAB//+AA///wAP//8AH///gB///4Af//+AH///gAAAAAAAAAAA='
};
const TEMPLATES={};
for(const [t,s] of Object.entries(TEMPLATE64)){const raw=atob(s),a=new Uint8Array(1024);for(let i=0;i<1024;i++)a[i]=(raw.charCodeAt(i>>3)>>(7-(i&7)))&1;TEMPLATES[t]=a;}
let S={dataUrl:null,img:null,rect:null,cells:null,start:null,line:[],positions:[],step:0,playing:false,timer:null,mateN:0,orientation:'black',debug:''};
function show(id){SCREENS.forEach(x=>$(x).classList.toggle('active',x===id));}
function prog(v,title,text){$('bar').style.width=Math.max(4,Math.min(100,v))+'%';if(title)$('procTitle').textContent=title;if(text)$('procText').textContent=text;}
function wait(ms){return new Promise(r=>setTimeout(r,ms));}
function fileData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file);});}
function loadImg(url){return new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=url;});}
function median(a){const b=[...a].sort((x,y)=>x-y),n=b.length;return n?(n&1?b[n>>1]:(b[(n>>1)-1]+b[n>>1])/2):0;}

function detectBoard(img){
 const maxW=480,W0=img.naturalWidth||img.width,H0=img.naturalHeight||img.height,scale=Math.min(1,maxW/W0),W=Math.round(W0*scale),H=Math.round(H0*scale);
 if(Math.abs(W-H)/Math.max(W,H)<.06)return{x:0,y:0,s:Math.min(W0,H0)};
 const cv=document.createElement('canvas');cv.width=W;cv.height=H;const ctx=cv.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,W,H);const p=ctx.getImageData(0,0,W,H).data;
 const sx=new Float64Array(W-1),sy=new Float64Array(H-1);const threshold=30;
 for(let y=0;y<H;y++)for(let x=0;x<W-1;x++){let d=0;const i=(y*W+x)*4,j=i+4;d=(Math.abs(p[j]-p[i])+Math.abs(p[j+1]-p[i+1])+Math.abs(p[j+2]-p[i+2]))/3;if(d>threshold)sx[x]++;sx[x]+=d*.03;}
 for(let y=0;y<H-1;y++)for(let x=0;x<W;x++){let d=0;const i=(y*W+x)*4,j=((y+1)*W+x)*4;d=(Math.abs(p[j]-p[i])+Math.abs(p[j+1]-p[i+1])+Math.abs(p[j+2]-p[i+2]))/3;if(d>threshold)sy[y]++;sy[y]+=d*.03;}
 function peaks(a,n,minDist){const ids=Array.from(a.keys()).sort((u,v)=>a[v]-a[u]),out=[];for(const i of ids){if(out.every(j=>Math.abs(i-j)>=minDist)){out.push(i);if(out.length>=n)break;}}return out;}
 const px=peaks(sx,20,8),py=peaks(sy,30,8);let best=null;
 for(let ia=0;ia<px.length;ia++)for(let ib=ia+1;ib<px.length;ib++){let xa=Math.min(px[ia],px[ib]),xb=Math.max(px[ia],px[ib]),dx=xb-xa;if(dx<W*.45)continue;for(let ja=0;ja<py.length;ja++)for(let jb=ja+1;jb<py.length;jb++){let ya=Math.min(py[ja],py[jb]),yb=Math.max(py[ja],py[jb]),dy=yb-ya,mis=Math.abs(dx-dy);if(mis>Math.max(8,dx*.04))continue;let sc=sx[xa]+sx[xb]+sy[ya]+sy[yb]-mis*30;if(!best||sc>best.sc)best={sc,xa,xb,ya,yb};}}
 if(!best)throw new Error('No encuentro un tablero 8×8 claro en la captura.');
 const side=Math.round(((best.xb-best.xa)+(best.yb-best.ya))/2),cx=(best.xa+best.xb)/2,cy=(best.ya+best.yb)/2,inv=1/scale;
 return{x:Math.max(0,Math.round((cx-side/2)*inv)),y:Math.max(0,Math.round((cy-side/2)*inv)),s:Math.round(side*inv)};
}

function largestComponent(mask,w,h){const seen=new Uint8Array(w*h);let best=[];const stack=[];for(let y=0;y<h;y++)for(let x=0;x<w;x++){let root=y*w+x;if(!mask[root]||seen[root])continue;let pts=[];stack.push(root);seen[root]=1;while(stack.length){let z=stack.pop();pts.push(z);let yy=(z/w)|0,xx=z-yy*w;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;let nx=xx+dx,ny=yy+dy;if(nx<0||nx>=w||ny<0||ny>=h)continue;let q=ny*w+nx;if(mask[q]&&!seen[q]){seen[q]=1;stack.push(q);}}}if(pts.length>best.length)best=pts;}const out=new Uint8Array(w*h);for(const z of best)out[z]=1;return{mask:out,pts:best};}
function normalizeMask(mask,w,h){let x0=w,y0=h,x1=-1,y1=-1;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(mask[y*w+x]){if(x<x0)x0=x;if(x>x1)x1=x;if(y<y0)y0=y;if(y>y1)y1=y;}const out=new Uint8Array(1024);if(x1<0)return out;let bw=x1-x0+1,bh=y1-y0+1,scale=Math.min(28/bw,28/bh),nw=Math.max(1,Math.round(bw*scale)),nh=Math.max(1,Math.round(bh*scale)),ox=((32-nw)/2)|0,oy=((32-nh)/2)|0;for(let yy=0;yy<nh;yy++)for(let xx=0;xx<nw;xx++){let sx=x0+Math.min(bw-1,Math.floor((xx+.5)/nw*bw)),sy=y0+Math.min(bh-1,Math.floor((yy+.5)/nh*bh));if(mask[sy*w+sx])out[(oy+yy)*32+ox+xx]=1;}return out;}
function iou(a,b){let inter=0,uni=0;for(let i=0;i<1024;i++){let x=a[i],y=b[i];if(x&&y)inter++;if(x||y)uni++;}return uni?inter/uni:0;}
function scanBoard(img,rect){
 const size=800,cv=document.createElement('canvas');cv.width=size;cv.height=size;const ctx=cv.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,rect.x,rect.y,rect.s,rect.s,0,0,size,size);const px=ctx.getImageData(0,0,size,size).data,cell=size/8,cells=[];
 for(let r=0;r<8;r++)for(let c=0;c<8;c++){const x0=Math.round(c*cell),y0=Math.round(r*cell),x1=Math.round((c+1)*cell),y1=Math.round((r+1)*cell),w=x1-x0,h=y1-y0,inset=Math.max(3,Math.round(Math.min(w,h)*.07)),samples=[];
   const corners=[[inset,inset],[w-inset-1,inset],[inset,h-inset-1],[w-inset-1,h-inset-1]];for(const [cx,cy] of corners)for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){let xx=Math.max(0,Math.min(w-1,cx+dx))+x0,yy=Math.max(0,Math.min(h-1,cy+dy))+y0,i=(yy*size+xx)*4;samples.push([px[i],px[i+1],px[i+2]]);}const bg=[median(samples.map(s=>s[0])),median(samples.map(s=>s[1])),median(samples.map(s=>s[2]))],mask=new Uint8Array(w*h);let bgL=.299*bg[0]+.587*bg[1]+.114*bg[2];
   for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++){let i=((y0+yy)*size+x0+xx)*4,dr=px[i]-bg[0],dg=px[i+1]-bg[1],db=px[i+2]-bg[2],dist=Math.sqrt(dr*dr+dg*dg+db*db)/441.67;if(dist>.13)mask[yy*w+xx]=1;}
   const comp=largestComponent(mask,w,h);if(comp.pts.length<w*h*.035){cells.push({empty:true,r,c});continue;}const nm=normalizeMask(comp.mask,w,h),ranked=TYPES.map(t=>({t,score:iou(nm,TEMPLATES[t])})).sort((a,b)=>b.score-a.score);if(ranked[0].score<.25){cells.push({empty:true,r,c});continue;}
   let light=0,dark=0;for(const z of comp.pts){let yy=(z/w)|0,xx=z-yy*w,i=((y0+yy)*size+x0+xx)*4,L=.299*px[i]+.587*px[i+1]+.114*px[i+2];if(L>bgL+25)light++;else if(L<bgL-25)dark++;}const color=light>dark*.4?'w':'b';cells.push({empty:false,r,c,color,alts:ranked.slice(0,3)});
 }
 return cells;
}
function cellsBoard(cells,useAlt={}){const b=Array(64).fill(null);for(let i=0;i<cells.length;i++){const c=cells[i];if(c.empty)continue;let ai=useAlt[i]||0,t=c.alts[Math.min(ai,c.alts.length-1)].t;b[c.r*8+c.c]=c.color==='w'?t.toUpperCase():t;}return b;}
function rotateBoard(b){return Array.from({length:64},(_,i)=>b[63-i]);}
function boardKey(b){return b.map(x=>x||'.').join('');}
function validShape(b){return b.filter(x=>x==='K').length===1&&b.filter(x=>x==='k').length===1&&b.filter(Boolean).length<=32;}
function preferredOrientation(cells){let topW=0,topB=0,botW=0,botB=0;for(const c of cells){if(c.empty)continue;if(c.r<2)c.color==='w'?topW++:topB++;if(c.r>5)c.color==='w'?botW++:botB++;}return botB>botW&&topW>topB?'black':botW>botB&&topB>topW?'white':'black';}

const pc=x=>x?(x===x.toUpperCase()?'w':'b'):null,pt=x=>x?x.toLowerCase():null,other=s=>s==='w'?'b':'w';
const rc=i=>[(i/8)|0,i%8],inside=(r,c)=>r>=0&&r<8&&c>=0&&c<8;
function sq(i){let [r,c]=rc(i);return'abcdefgh'[c]+(8-r);}
function kingIndex(b,side){const k=side==='w'?'K':'k';return b.indexOf(k);}
function attacked(b,target,by){const [r,c]=rc(target),pawn=by==='w'?'P':'p';let pr=r+(by==='w'?1:-1);for(const dc of[-1,1])if(inside(pr,c+dc)&&b[pr*8+c+dc]===pawn)return true;const n=by==='w'?'N':'n';for(const[dR,dC]of[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]]){let rr=r+dR,cc=c+dC;if(inside(rr,cc)&&b[rr*8+cc]===n)return true;}const k=by==='w'?'K':'k';for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;let rr=r+dr,cc=c+dc;if(inside(rr,cc)&&b[rr*8+cc]===k)return true;}const dirs=[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]];for(let di=0;di<dirs.length;di++){let[dr,dc]=dirs[di],rr=r+dr,cc=c+dc;while(inside(rr,cc)){let p=b[rr*8+cc];if(p){if(pc(p)===by){let t=pt(p);if(t==='q'||(di<4&&t==='r')||(di>=4&&t==='b'))return true;}break;}rr+=dr;cc+=dc;}}return false;}
function inCheck(pos,side=pos.side){let k=kingIndex(pos.b,side);return k<0||attacked(pos.b,k,other(side));}
function pseudoMoves(pos){const b=pos.b,side=pos.side,m=[];for(let from=0;from<64;from++){let p=b[from];if(!p||pc(p)!==side)continue;let t=pt(p),[r,c]=rc(from);const add=(to,prom=null)=>{let cap=b[to];if(cap&&pt(cap)==='k')return;m.push({from,to,piece:p,capture:cap||null,promotion:prom});};if(t==='p'){let dir=side==='w'?-1:1,nr=r+dir;if(inside(nr,c)&&!b[nr*8+c]){if(nr===0||nr===7){for(const q of['q','r','b','n'])add(nr*8+c,q);}else add(nr*8+c);let sr=side==='w'?6:1,nr2=r+2*dir;if(r===sr&&!b[nr2*8+c])add(nr2*8+c);}for(const dc of[-1,1]){let rr=r+dir,cc=c+dc;if(!inside(rr,cc))continue;let to=rr*8+cc;if(b[to]&&pc(b[to])!==side){if(rr===0||rr===7){for(const q of['q','r','b','n'])add(to,q);}else add(to);}}}else if(t==='n'){for(const[dr,dc]of[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]]){let rr=r+dr,cc=c+dc;if(inside(rr,cc)&&(!b[rr*8+cc]||pc(b[rr*8+cc])!==side))add(rr*8+cc);}}else if(t==='k'){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;let rr=r+dr,cc=c+dc;if(inside(rr,cc)&&(!b[rr*8+cc]||pc(b[rr*8+cc])!==side))add(rr*8+cc);}}else{let ds=t==='b'?[[1,1],[1,-1],[-1,1],[-1,-1]]:t==='r'?[[1,0],[-1,0],[0,1],[0,-1]]:[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]];for(const[dr,dc]of ds){let rr=r+dr,cc=c+dc;while(inside(rr,cc)){let to=rr*8+cc;if(!b[to])add(to);else{if(pc(b[to])!==side)add(to);break;}rr+=dr;cc+=dc;}}}}return m;}
function makeMove(pos,m){const b=pos.b.slice();let p=b[m.from];b[m.from]=null;if(m.promotion)p=pos.side==='w'?m.promotion.toUpperCase():m.promotion;b[m.to]=p;return{b,side:other(pos.side)};}
function legalMoves(pos){const us=pos.side,out=[];for(const m of pseudoMoves(pos)){const n=makeMove(pos,m),k=kingIndex(n.b,us);if(k>=0&&!attacked(n.b,k,other(us)))out.push(m);}return out;}
function checkMate(pos){const ms=legalMoves(pos);return ms.length===0&&inCheck(pos,pos.side);}
function posKey(pos,rem){return boardKey(pos.b)+'|'+pos.side+'|'+rem;}
function givesCheck(pos,m){const n=makeMove(pos,m);return inCheck(n,n.side);}
function forcedMate(pos,attacker,rem,deadline,checksOnly,memo){if(performance.now()>deadline)throw new Error('TIMEOUT');const moves=legalMoves(pos);if(!moves.length)return inCheck(pos,pos.side)&&pos.side!==attacker?[]:null;if(pos.side===attacker&&rem<=0)return null;let key=posKey(pos,rem)+'|'+(checksOnly?1:0);if(memo.has(key))return memo.get(key);if(pos.side===attacker){let ordered=moves.map(m=>({m,ch:givesCheck(pos,m)})).sort((a,b)=>Number(b.ch)-Number(a.ch));if(checksOnly)ordered=ordered.filter(x=>x.ch);for(const x of ordered){const n=makeMove(pos,x.m),sub=forcedMate(n,attacker,rem-1,deadline,checksOnly,memo);if(sub!==null){const ans=[x.m,...sub];memo.set(key,ans);return ans;}}memo.set(key,null);return null;}else{let worst=[];for(const m of moves){const n=makeMove(pos,m),sub=forcedMate(n,attacker,rem,deadline,checksOnly,memo);if(sub===null){memo.set(key,null);return null;}const cand=[m,...sub];if(cand.length>worst.length)worst=cand;}memo.set(key,worst);return worst;}}
function findMate(board,side,maxDepth=5,ms=1800){if(!validShape(board))return null;let pos={b:board.slice(),side},deadline=performance.now()+ms;for(let d=1;d<=maxDepth;d++){try{let line=forcedMate(pos,side,d,deadline,true,new Map());if(line)return{line,mate:d,pos};}catch(e){if(e.message==='TIMEOUT')return null;throw e;}}return null;}
function moveSAN(pos,m){let t=pt(m.piece),capture=!!m.capture,prefix='';if(t==='p'){if(capture)prefix='abcdefgh'[m.from%8]+'x';}else{prefix=t.toUpperCase();const same=legalMoves(pos).filter(x=>x.from!==m.from&&pt(x.piece)===t&&x.to===m.to);if(same.length){let ff=m.from%8,fr=(m.from/8)|0,fileUnique=same.every(x=>x.from%8!==ff),rankUnique=same.every(x=>((x.from/8)|0)!==fr);prefix+=fileUnique?'abcdefgh'[ff]:rankUnique?String(8-fr):sq(m.from);}if(capture)prefix+='x';}let s=prefix+sq(m.to);if(m.promotion)s+='='+m.promotion.toUpperCase();const n=makeMove(pos,m);if(inCheck(n,n.side))s+=legalMoves(n).length===0?'#':'+';return s;}
function annotate(start,line){let pos={b:start.b.slice(),side:start.side},out=[];for(const m of line){out.push({...m,san:moveSAN(pos,m)});pos=makeMove(pos,m);}return out;}
function notation(line,startSide){let no=1,side=startSide,parts=[];for(const m of line){if(side==='w'){parts.push(no+'. '+m.san);side='b';}else{parts.push(no+'... '+m.san);no++;side='w';}}return parts.join(' ');}
function fenBoard(b){let rows=[];for(let r=0;r<8;r++){let s='',n=0;for(let c=0;c<8;c++){let p=b[r*8+c];if(!p)n++;else{if(n){s+=n;n=0;}s+=p;}}if(n)s+=n;rows.push(s);}return rows.join('/');}

async function solveCells(cells){const base=cellsBoard(cells),pref=preferredOrientation(cells),order=pref==='black'?[{b:rotateBoard(base),o:'black'},{b:base,o:'white'}]:[{b:base,o:'white'},{b:rotateBoard(base),o:'black'}];let tries=0;for(const item of order)for(const side of[item.o==='black'?'b':'w',item.o==='black'?'w':'b']){tries++;prog(62,'Buscando el mate','Probando orientación y turno...');await wait(0);let hit=findMate(item.b,side,5,2200);if(hit)return{...hit,orientation:item.o,tries};}
 const uncertain=[];for(let i=0;i<cells.length;i++){let c=cells[i];if(c.empty||c.alts.length<2)continue;let margin=c.alts[0].score-c.alts[1].score;if(margin<.14||c.alts[0].score<.76)uncertain.push({i,margin});}uncertain.sort((a,b)=>a.margin-b.margin);let variants=[];for(const u of uncertain.slice(0,9)){for(let alt=1;alt<Math.min(3,cells[u.i].alts.length);alt++){let use={};use[u.i]=alt;variants.push({use,pen:cells[u.i].alts[0].score-cells[u.i].alts[alt].score});}}for(let a=0;a<Math.min(6,uncertain.length);a++)for(let b=a+1;b<Math.min(6,uncertain.length);b++){let use={};use[uncertain[a].i]=1;use[uncertain[b].i]=1;variants.push({use,pen:uncertain[a].margin+uncertain[b].margin});}variants.sort((a,b)=>a.pen-b.pen);for(const v of variants.slice(0,70)){let bb=cellsBoard(cells,v.use);if(!validShape(bb))continue;for(const item of(pref==='black'?[{b:rotateBoard(bb),o:'black'},{b:bb,o:'white'}]:[{b:bb,o:'white'},{b:rotateBoard(bb),o:'black'}]))for(const side of[item.o==='black'?['b','w']:['w','b']]){tries++;if(tries%5===0){prog(70,'Corrigiendo lecturas dudosas','Comprobando alternativas...');await wait(0);}let hit=findMate(item.b,side,5,500);if(hit)return{...hit,orientation:item.o,tries};}}
 return null;}
function renderBoard(board,orientation,last){const files=orientation==='black'?'hgfedcba':'abcdefgh',ranks=orientation==='black'?'12345678':'87654321';$('board').innerHTML='';for(let vr=0;vr<8;vr++)for(let vc=0;vc<8;vc++){let br=orientation==='black'?7-vr:vr,bc=orientation==='black'?7-vc:vc,name='abcdefgh'[bc]+(8-br),el=document.createElement('div');el.className='sq '+(((vr+vc)&1)?'dark':'light');if(last&&last.from===br*8+bc)el.classList.add('lastFrom');if(last&&last.to===br*8+bc)el.classList.add('lastTo');let p=board[br*8+bc];if(p){let sp=document.createElement('span');sp.className='piece';sp.textContent=GLYPH[p];el.appendChild(sp);}if(vc===0){let s=document.createElement('span');s.className='coord rank';s.textContent=ranks[vr];el.appendChild(s);}if(vr===7){let s=document.createElement('span');s.className='coord file';s.textContent=files[vc];el.appendChild(s);}$('board').appendChild(el);}}
function stopPlay(){S.playing=false;clearTimeout(S.timer);S.timer=null;$('play').textContent='▶ Play';}
function gotoStep(n){S.step=Math.max(0,Math.min(S.positions.length-1,n));let last=S.step?S.line[S.step-1]:null;renderBoard(S.positions[S.step].b,S.orientation,last);}
async function playLoop(){if(!S.playing)return;if(S.step>=S.positions.length-1){stopPlay();return;}gotoStep(S.step+1);S.timer=setTimeout(playLoop,Number($('speed').value));}
function togglePlay(){if(S.playing){stopPlay();return;}if(S.step>=S.positions.length-1)gotoStep(0);S.playing=true;$('play').textContent='❚❚ Pausa';S.timer=setTimeout(playLoop,120);}
async function analyze(url){stopPlay();S.dataUrl=url;show('processing');$('procImg').src=url;prog(7,'Leyendo el puzzle','Buscando el tablero...');try{const img=await loadImg(url);S.img=img;await wait(30);const rect=detectBoard(img);S.rect=rect;prog(30,'Tablero encontrado','Reconociendo las piezas localmente...');await wait(20);const cells=scanBoard(img,rect);S.cells=cells;let pieces=cells.filter(c=>!c.empty).length;if(pieces<4)throw new Error('He encontrado el tablero, pero no reconozco suficientes piezas.');prog(52,'Piezas reconstruidas','Buscando un mate forzado...');await wait(30);const solved=await solveCells(cells);if(!solved)throw new Error('He reconstruido '+pieces+' piezas, pero no encuentro un mate forzado de hasta 5 jugadas.');S.orientation=solved.orientation;S.start=solved.pos;S.line=annotate(solved.pos,solved.line);S.mateN=solved.mate;S.positions=[{b:solved.pos.b.slice(),side:solved.pos.side}];let pos={b:solved.pos.b.slice(),side:solved.pos.side};for(const m of S.line){pos=makeMove(pos,m);S.positions.push({b:pos.b.slice(),side:pos.side});}S.step=0;S.debug='Tablero: '+fenBoard(solved.pos.b)+' '+solved.pos.side+' | '+pieces+' piezas | '+solved.tries+' intentos';$('problemText').textContent=(solved.pos.side==='b'?'Negras':'Blancas')+' mueven · mate forzado';$('mate').textContent='Mate en '+S.mateN;$('line').textContent=notation(S.line,solved.pos.side);renderBoard(S.positions[0].b,S.orientation,null);prog(100,'Listo','');await wait(150);show('result');}catch(e){console.error(e);$('errorText').textContent=e.message||'No he podido resolver esta captura.';$('details').textContent='Todo se ha ejecutado localmente. '+(S.rect?'Tablero detectado en x '+S.rect.x+', y '+S.rect.y+', '+S.rect.s+' px. ':'')+(S.debug||'');show('error');}}
$('picker').addEventListener('change',async e=>{const f=e.target.files&&e.target.files[0];if(!f)return;const u=await fileData(f);e.target.value='';analyze(u);});
$('cancel').onclick=()=>show('home');$('back').onclick=()=>{stopPlay();show('home');};$('errorBack').onclick=()=>show('home');$('play').onclick=togglePlay;$('prev').onclick=()=>{stopPlay();gotoStep(S.step-1);};$('next').onclick=()=>{stopPlay();gotoStep(S.step+1);};
$('copy').onclick=async()=>{let t=notation(S.line,S.start.side);try{await navigator.clipboard.writeText(t);$('copy').textContent='Copiado ✓';setTimeout(()=>$('copy').textContent='Copiar solución',1100);}catch(e){}};
$('share').onclick=async()=>{let t='Mate en '+S.mateN+'\n'+notation(S.line,S.start.side);if(navigator.share){try{await navigator.share({title:'Chess puzzle solution',text:t});return;}catch(e){}}try{await navigator.clipboard.writeText(t);}catch(e){}$('share').textContent='Copiado ✓';setTimeout(()=>$('share').textContent='Compartir',1100);};
